const productsData = {
  fruits_veggies: [
    { name: "Rasakadali", weight: "10 Kg", img: "images/Rasakadali.jpg" },
    { name: "Ivy Gourd Small", weight: "5 Kg", img: "images/Ivy Gourd Small.jpg" },
    { name: "Snake Gourd", weight: "5 Kg", img: "images/Snake Gourd.jpg" },
    { name: "Gooseberry India", weight: "5 Kg", img: "images/Gooseberry.jpg" },
    { name: "Red Pumpkin", weight: "5 Kg", img: "images/Red Pumpkin.jpg" },
    { name: "Colocasia Small", weight: "5 Kg", img: "images/Colocasia Small.jpg" },
    { name: "Bottlegourd Small", weight: "5 Kg", img: "images/Bottlegourd Small.jpg" },
    { name: "Cluster Beans", weight: "5 Kg", img: "images/Cluster Beans.jpg" },
    { name: "Elephant Foot Yam", weight: "10 Kg", img: "images/Elephant Foot Yam.jpg" },
    { name: "Sweet Potato Red", weight: "5 Kg", img: "images/Sweet Potato Red.jpg" },
    { name: "Sweet Potato White", weight: "5 Kg", img: "images/Sweet Potato White.jpg" },
    { name: "Long Beans", weight: "5 Kg", img: "images/Long Beans.jpg" },
    { name: "Yellow Cucumber", weight: "10 Kg", img: "images/Yellow Cucumber.jpg" },
    { name: "Shallots", weight: "10 Kg", img: "images/Shallots.jpg" },
    { name: "Guava", weight: "5 Kg", img: "images/Guava.jpg" },
    { name: "Jack Fruit", weight: "5 Kg", img: "images/Jack Fruit.jpg" },
    { name: "Mango Kesar", weight: "2 Kg", img: "images/Mango Kesar.jpg" },
    { name: "Mango Badami", weight: "2 Kg", img: "images/Mango Badami.jpg" },
    { name: "Bitter Gourd Green", weight: "5 Kg", img: "images/Bitter Gourd Green.jpg" },
    { name: "Okra", weight: "5 Kg", img: "images/Okra.jpg" },
    { name: "Banana Flower", weight: "5 Kg", img: "images/Banana Flower.jpg" },
    { name: "Chinese Potato", weight: "5 Kg", img: "images/Chinese Potato.jpg" },
    { name: "Banana Stump", weight: "5 Kg", img: "images/Banana Stump.jpg" },
    { name: "Tapioka", weight: "5 Kg", img: "images/Tapioka.jpg" },
    { name: "Rambutan", weight: "10 Kg", img: "images/Rambutan.jpg" },
    { name: "Mangostein", weight: "10 Kg", img: "images/Mangostein.jpg" },
    { name: "Passion Fruit", weight: "10 Kg", img: "images/Passion Fruit.jpg" },
    { name: "Ginger", weight: "5 Kg", img: "images/Ginger.jpg" },
    { name: "Garlic Small", weight: "5 Kg", img: "images/Garlic Small.jpg" },
    { name: "Chow Chow (Chayote)", weight: "5 Kg", img: "images/Chow Chow (Chayote).jpg" },
    { name: "Turmeric", weight: "5 Kg", img: "images/Turmeric.jpg" },
    { name: "Drumstick", weight: "5 Kg", img: "images/Drumstick.jpg" },
    { name: "Green Banana", weight: "10 Kg", img: "images/Green Banana.jpg" },
    { name: "Curry Banana", weight: "10 Kg", img: "images/Curry Banana.jpg" },
    { name: "Ridge Gourd Small", weight: "5 Kg", img: "images/Ridge Gourd Small.jpg" },
    { name: "Ash Gourd", weight: "5 Kg", img: "images/Ash Gourd.jpg" },
    { name: "Brinjol Pink Ball Small", weight: "5 Kg", img: "images/Brinjol Pink Ball Small.jpg" },
    { name: "Brinjol Pink Long", weight: "5 Kg", img: "images/Brinjol Pink Long.jpg" },
    { name: "Brinjol Pink Ball Lines", weight: "5 Kg", img: "images/Brinjol Pink Ball Lines.jpg" },
    { name: "Drumstick Leaves", weight: "5 Kg", img: "images/Drumstick Leaves.jpg" },
    { name: "Raw Mango(Green)", weight: "5 Kg", img: "images/Mango(Green).jpg" },
    { name: "Banana Leaf", weight: "5 Kg", img: "images/Banana Leaf.jpg" },
    { name: "Chineese Potato(Koorka)", weight: "5 Kg", img: "images/Chinese Potato.jpg" },
    { name: "Bread Fruit", weight: "5 Kg", img: "images/BreadFruit.jpg" },
    { name: "Tender JackFruit", weight: "5 Kg", img: "images/TenderJackFruit.jpg" },
    { name: "Sotapuri Mango", weight: "5 Kg", img: "images/Sotapuri Mango.jpg" },
    { name: "Red Saag", weight: "5 Kg", img: "images/Red Saag.jpg" },
    { name: "Pananongu", weight: "5 Kg", img: "images/Pananongu.jpg" },
    { name: "Chinese Spinach", weight: "5 Kg", img: "images/Chinese Spinach.jpg" },
    { name: "Ridge Guard Small", weight: "5 Kg", img: "images/Ridge Guard Small.jpg" },

  ],

  pulses: [
    { name: "Toor Dal", weight: "5 Kg", img: "images/Toor Dal.jpg" },
    { name: "Green Gram", weight: "5 Kg", img: "images/Green Gram.jpg" },
    { name: "Chana Dal", weight: "5 Kg", img: "images/Chana Dal.jpg" },
    { name: "Masoor Dal", weight: "5 Kg", img: "images/Masoor Dal.jpg" },
    { name: "Urad Dal", weight: "5 Kg", img: "images/Urad Dal.jpg" },
    { name: "Rajma", weight: "5 Kg", img: "images/Rajma.jpg" },
    { name: "Moth Beans", weight: "5 Kg", img: "images/Moth Beans.jpg" }
  ],

  rice: [
    { name: "Palakadan Matta", weight: "5/10 Kg", img: "images/Palakadan Matta.jpg" },
    { name: "Jeera Rice", weight: "5/10 Kg", img: "images/Jeera Rice.jpg" },
    { name: "Thanjoar Ponni", weight: "5/10 Kg", img: "images/Thanjoar Ponni.jpg" },
    { name: "Idli Rice", weight: "5/10 Kg", img: "images/Idli Rice.jpg" }
  ]
};
